# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:{{port}}/api/activities
Content-Type: application/json

{
  "title": "Baseball en folie",
  "summary": "Jouer au baseball en criant comme des fous !"
}

###

GET http://localhost:{{port}}/api/activities?titleContains=foot
Accept: application/json

###

GET http://localhost:{{port}}/api/activities
Accept: application/json

###

PUT http://localhost:{{port}}/api/activities
Content-Type: application/json

{
  "id": 5,
  "title": "Football en folie",
  "summary": "Jouer au baseball en criant comme des fous !"
}

###
POST http://localhost:{{port}}/api/activities/5/resources
Content-Type: application/json

{
  "resourceId": 4
}

###