# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:{{port}}/api/activities
Content-Type: application/json
Cookie: {{cookie_session}}

{
  "title": "Baseball en folie",
  "summary": "Jouer au baseball en criant comme des fous !"
}

###
POST http://localhost:{{port}}/api/activities
Content-Type: application/json
Cookie: {{cookie_session}}

{
  "title": "",
  "summary": ""
}

###

GET http://localhost:{{port}}/api/activities?titleContains=foot
Accept: application/json
Cookie: {{cookie_session}}

###

GET http://localhost:{{port}}/api/activities
Accept: application/json
Cookie: {{cookie_session}}

###

PUT http://localhost:{{port}}/api/activities/2
Content-Type: application/json
Cookie: {{cookie_session}}

{
  "title": "Updated activity",
  "summary": "Updated activity summary"
}

###
GET http://localhost:{{port}}/api/activities/2
Content-Type: application/json
Cookie: {{cookie_session}}

###
POST http://localhost:{{port}}/api/activities/2/resources
Content-Type: application/json
Cookie: {{cookie_session}}

{
  "resourceId": 2,
  "quantity": 15
}

###