# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);
POST http://localhost:{{port}}/users/registration
Content-Type: application/json

{
  "username": "bob",
  "password": "bob123"
}

###
POST http://localhost:{{port}}/users/newSession
Content-Type: application/x-www-form-urlencoded

user=bob&password=bob123

> {%
client.assert(response.status === 302, "invalid status code returned");
client.global.set("cookie_session", response.headers.valueOf("Set-Cookie"));
 %}

###
POST http://localhost:{{port}}/users/registration
Content-Type: application/json

{
  "username": "tod",
  "password": "tod123"
}

###
POST http://localhost:{{port}}/users/newSession
Content-Type: application/x-www-form-urlencoded

user=tod&password=tod123

> {%
client.assert(response.status === 302, "invalid status code returned");
client.global.set("cookie_session", response.headers.valueOf("Set-Cookie"));
 %}

###
